### ISSUE TITLE
Images are not provided

### ISSUE THREAD

**Issue by BadWolf19** [StandardV/Ads-Click-Automation#2]
You didn't provide all the pictures needed, you only gave in 5 and the names were wrong, other then that good work and I'm hoping to try it out soon!

**Comment by StandardV** [comment]
Thank you for your request, I've changed and update the images along with the name, feel free to let me know in case there's any other issue for you

**Comment by BadWolf19** [comment]
Seems to kind of work, not that well.
Its a little to complicated having to use the Region collector and adding it to everything to make it work for myself. Have you looking into the API? Maybe you could make some type of ad bot type thing using it which will make stuff a lot easier, thank you

**Comment by StandardV** [comment]
You can actually set majority of them to the full game screen of the blue stack, what I did just to minimize process time for the pyautogui and make it easier for it to look at the image though , beside the clicking home page button at line 271 (click(291.20)) and detect mark up color of Audacity at line 115 and line 122 is stationary most of them can be modify region into the blue stack screen but still keep about 70% efficiency though

**Comment by StandardV** [comment]
It work 100% of the time for me, but I'll make a full document on how it work now , I've considered using API but it's not that efficient and fast in term of creating the script so used this.

**Comment by BadWolf19** [comment]
I'll try it out, thank you for your efforts on helping me, also with using the API you could probably have multiple accounts using the program and not just one, along without having your pc being unusable for the time you are watching ads

**Comment by StandardV** [comment]
I'm using a dual monitor and since it return the cursor to where it was after clicks, it's not that much of a problem for me. But the API you mentioned seem really interesting, can you please share what it is? I'd try look into it and see what I could do

**Comment by BadWolf19** [comment]
I don't personally know anything of how the API works or where to find it, all I know is that plenty of people are using it for ad bots on several accounts and transferring a ton of bux later

**Comment by StandardV** [comment]
If that's the case, I'd do some research and work on it later if I have free time then. I'm currently doing a stream snipe script for valorant, if interested you could wait for more update. Now, if there is no other concern, I'd go ahead and mark this as closed. Just open another Issue if there are any other problems that you encountered
